insert into article(title, link, content, date) values
  ('Object Oriented Rails ? Writing better controllers', 'http://pivotallabs.com/object-oriented-rails-writing-better-controllers/', '<p>I have been doing a lot of mobile development lately, using Objective-C on iOS, and Java on Android. Since I&#8217;m also a Ruby developer, it makes a lot of sense for me to try and apply what I learn from each of these languages and frameworks whenever I can. Todayaaa</p>
<p>The post <a rel="nofollow" href="http://pivotallabs.com/object-oriented-rails-writing-better-controllers/">Object Oriented Rails &#8211; Writing better controllers</a> appeared first on <a rel="nofollow" href="http://pivotallabs.com">Pivotal Labs</a>.</p>', '2013-06-30T01:44:33Z')
  ,
('Object Oriented Rails ? Writing better controllers', 'http://pivotallabs.com/object-oriented-rails-writing-better-controllers/', '<p>I have been doing a lot of mobile development lately, using Objective-C on iOS, and Java on Android. Since I&#8217;m also a Ruby developer, it makes a lot of sense for me to try and apply what I learn from each of these languages and frameworks whenever I can. Todayaaa</p>
<p>The post <a rel="nofollow" href="http://pivotallabs.com/object-oriented-rails-writing-better-controllers/">Object Oriented Rails &#8211; Writing better controllers</a> appeared first on <a rel="nofollow" href="http://pivotallabs.com">Pivotal Labs</a>.</p>', '2013-06-30T01:44:33Z')
  ,
  ('Object Oriented Rails ? Writing better controllers', 'http://pivotallabs.com/object-oriented-rails-writing-better-controllers/', '<p>I have been doing a lot of mobile development lately, using Objective-C on iOS, and Java on Android. Since I&#8217;m also a Ruby developer, it makes a lot of sense for me to try and apply what I learn from each of these languages and frameworks whenever I can. Todayaaa</p>
<p>The post <a rel="nofollow" href="http://pivotallabs.com/object-oriented-rails-writing-better-controllers/">Object Oriented Rails &#8211; Writing better controllers</a> appeared first on <a rel="nofollow" href="http://pivotallabs.com">Pivotal Labs</a>.</p>', '2013-06-30T01:44:33Z')
  ,
  ('Object Oriented Rails ? Writing better controllers', 'http://pivotallabs.com/object-oriented-rails-writing-better-controllers/', '<p>I have been doing a lot of mobile development lately, using Objective-C on iOS, and Java on Android. Since I&#8217;m also a Ruby developer, it makes a lot of sense for me to try and apply what I learn from each of these languages and frameworks whenever I can. Todayaaa</p>
<p>The post <a rel="nofollow" href="http://pivotallabs.com/object-oriented-rails-writing-better-controllers/">Object Oriented Rails &#8211; Writing better controllers</a> appeared first on <a rel="nofollow" href="http://pivotallabs.com">Pivotal Labs</a>.</p>', '2013-06-30T01:44:33Z')
;
